# Generated by Django 5.1.6 on 2025-04-23 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson_next_lesson_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='next_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_lessons', to='courses.lesson'),
        ),
    ]
