# Generated by Django 5.1.6 on 2025-05-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to='video/', verbose_name='Видео'),
        ),
    ]
