# Generated by Django 5.1.6 on 2025-05-15 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='video_url',
            new_name='video_file',
        ),
    ]
